---
- name: configuration check
  block:
    - name: check squid configuration
      command: squid -k check
      ignore_errors: true
      register: squid_syntax_check
      changed_when: false

    - name: show errors
      debug:
        msg: "{{ squid_syntax_check.stderr }}"
      when: squid_syntax_check.rc != 0

    - name: Notify if bad syntax
      assert:
        that:
          - squid_syntax_check.rc == 0
        fail_msg: "Squid configuration check failed. You should check debug information above and fix the problem(s)."

    - name: restart squid
      service:
        name: squid
        state: restarted
      when: squid_syntax_check.rc == 0
  when: not ansible_check_mode
